apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: argocdtlsspc
  namespace: argocd
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "b644be55-ab2d-408d-b495-fb0a2c82de44"
    keyvaultName: proj1devkv01
    tenantId: "183eb640-5eac-4ecb-8fea-f04b206445a5"
    objects: |
      array:
        - |
          objectName: proj1devargocdcert
          objectType: secret
          objectFormat: pem
  secretObjects:
    - secretName: argocd-server-tls
      type: kubernetes.io/tls
      data:
        - objectName: proj1devargocdcert
          key: tls.key
        - objectName: proj1devargocdcert
          key: tls.crt
